maintainer       "boundary"
maintainer_email "j@boundary.com"
license          "all rights reserved"
description      "Installs/Configures various apps"
long_description "Installs/Configures various apps"
version          "0.1"
